export const mockProperties = [
  // Delhi NCR Properties
  {
    id: 1,
    name: "DLF Camellias",
    location: "Golf Course Road, Gurgaon",
    city: "Gurgaon",
    price: 12,
    priceUnit: "Crore",
    currency: "INR",
    type: "Luxury Apartment",
    bedrooms: 4,
    size: 6000,
    status: "Ready to Move",
    builder: "DLF",
    features: ["Private Terrace", "Concierge", "Smart Home"],
    image: "/properties/dlf-camellias.jpg"
  },
  {
    id: 2,
    name: "Godrej Summit",
    location: "Sector 54, Gurgaon",
    city: "Gurgaon",
    price: 2.5,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 3,
    size: 2100,
    status: "Ready to Move",
    builder: "Godrej Properties",
    features: ["Clubhouse", "Swimming Pool", "Kids Play Area"],
    image: "/properties/godrej-summit.jpg"
  },
  {
    id: 3,
    name: "M3M Golf Estate",
    location: "Sector 65, Gurgaon",
    city: "Gurgaon",
    price: 3.2,
    priceUnit: "Crore",
    currency: "INR",
    type: "Penthouse",
    bedrooms: 4,
    size: 3500,
    status: "Under Construction",
    builder: "M3M",
    features: ["Golf Course View", "Private Pool", "Home Automation"],
    image: "/properties/m3m-golf.jpg"
  },
  {
    id: 4,
    name: "ATS Triumph",
    location: "Sector 104, Noida",
    city: "Noida",
    price: 1.8,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 3,
    size: 1950,
    status: "Ready to Move",
    builder: "ATS",
    features: ["Amphitheater", "Yoga Deck", "Jogging Track"],
    image: "/properties/ats-triumph.jpg"
  },

  // Mumbai Metropolitan Region
  {
    id: 5,
    name: "Lodha Bellissimo",
    location: "Worli, South Mumbai",
    city: "Mumbai",
    price: 8.5,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 3,
    size: 2500,
    status: "Ready to Move",
    builder: "Lodha Group",
    features: ["Sea View", "Infinity Pool", "Sky Lounge"],
    image: "/properties/lodha-bellissimo.jpg"
  },
  {
    id: 6,
    name: "Raheja Vivarea",
    location: "Mahalaxmi, Mumbai",
    city: "Mumbai",
    price: 22,
    priceUnit: "Crore",
    currency: "INR",
    type: "Luxury Apartment",
    bedrooms: 4,
    size: 4500,
    status: "Ready to Move",
    builder: "Raheja",
    features: ["Private Theatre", "Wine Cellar", "Butler Service"],
    image: "/properties/raheja-vivarea.jpg"
  },
  {
    id: 7,
    name: "Prestige Seawoods",
    location: "Seawoods, Navi Mumbai",
    city: "Navi Mumbai",
    price: 1.2,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 2,
    size: 1200,
    status: "Ready to Move",
    builder: "Prestige Group",
    features: ["Mall Connectivity", "Children's Play Area", "Gym"],
    image: "/properties/prestige-seawoods.jpg"
  },

  // Bangalore Properties
  {
    id: 8,
    name: "Brigade Metropolis",
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    price: 2.1,
    priceUnit: "Crore",
    currency: "INR",
    type: "Villa",
    bedrooms: 4,
    size: 2800,
    status: "Ready to Move",
    builder: "Brigade Group",
    features: ["Private Garden", "Clubhouse", "Swimming Pool"],
    image: "/properties/brigade-metropolis.jpg"
  },
  {
    id: 9,
    name: "Sobha City",
    location: "Thanisandra, Bangalore",
    city: "Bangalore",
    price: 1.5,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 3,
    size: 1850,
    status: "Under Construction",
    builder: "Sobha",
    features: ["Sports Complex", "Meditation Zone", "Retail Plaza"],
    image: "/properties/sobha-city.jpg"
  },

  // Hyderabad Properties
  {
    id: 10,
    name: "Aparna Cyberlife",
    location: "Gachibowli, Hyderabad",
    city: "Hyderabad",
    price: 1.8,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 3,
    size: 1950,
    status: "Ready to Move",
    builder: "Aparna Constructions",
    features: ["Tech-enabled Homes", "Co-working Space", "Skylounge"],
    image: "/properties/aparna-cyberlife.jpg"
  },
  {
    id: 11,
    name: "Prestige High Fields",
    location: "Kokapet, Hyderabad",
    city: "Hyderabad",
    price: 2.3,
    priceUnit: "Crore",
    currency: "INR",
    type: "Villa",
    bedrooms: 4,
    size: 3200,
    status: "Under Construction",
    builder: "Prestige Group",
    features: ["Organic Farm", "Gymnasium", "Party Lawn"],
    image: "/properties/prestige-highfields.jpg"
  },

  // Pune Properties
  {
    id: 12,
    name: "Lodha Belmondo",
    location: "Pune-Mumbai Expressway",
    city: "Pune",
    price: 1.2,
    priceUnit: "Crore",
    currency: "INR",
    type: "Villa",
    bedrooms: 3,
    size: 2400,
    status: "Ready to Move",
    builder: "Lodha Group",
    features: ["Golf Course", "Equestrian Center", "Adventure Sports"],
    image: "/properties/lodha-belmondo.jpg"
  },
  {
    id: 13,
    name: "Kolte Patil Life Republic",
    location: "Wagholi, Pune",
    city: "Pune",
    price: 85,
    priceUnit: "Lakh",
    currency: "INR",
    type: "Apartment",
    bedrooms: 2,
    size: 1100,
    status: "Ready to Move",
    builder: "Kolte Patil",
    features: ["Central Park", "Shopping Street", "Cycling Track"],
    image: "/properties/kp-life-republic.jpg"
  },

  // Chennai Properties
  {
    id: 14,
    name: "Casagrand Builder's Capitol",
    location: "OMR, Chennai",
    city: "Chennai",
    price: 1.5,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 3,
    size: 1800,
    status: "Ready to Move",
    builder: "Casagrand",
    features: ["Infinity Pool", "Cafeteria", "Indoor Games"],
    image: "/properties/casagrand-capital.jpg"
  },

  // Tier 2 Cities - Ahmedabad
  {
    id: 15,
    name: "Adani Shantigram",
    location: "S.G. Highway, Ahmedabad",
    city: "Ahmedabad",
    price: 95,
    priceUnit: "Lakh",
    currency: "INR",
    type: "Villa",
    bedrooms: 3,
    size: 2000,
    status: "Ready to Move",
    builder: "Adani Realty",
    features: ["Township", "Clubhouse", "Retail Plaza"],
    image: "/properties/adani-shantigram.jpg"
  },

  // Tier 2 Cities - Kolkata
  {
    id: 16,
    name: "Unitech Uniworld City",
    location: "New Town, Kolkata",
    city: "Kolkata",
    price: 1.1,
    priceUnit: "Crore",
    currency: "INR",
    type: "Apartment",
    bedrooms: 3,
    size: 1650,
    status: "Ready to Move",
    builder: "Unitech",
    features: ["Lake View", "Amphitheater", "Badminton Court"],
    image: "/properties/unitech-uniworld.jpg"
  },

  // Tier 3 Cities - Jaipur
  {
    id: 17,
    name: "Goyal Orchid White",
    location: "Sitapura, Jaipur",
    city: "Jaipur",
    price: 65,
    priceUnit: "Lakh",
    currency: "INR",
    type: "Apartment",
    bedrooms: 2,
    size: 1050,
    status: "Ready to Move",
    builder: "Goyal Group",
    features: ["Landscaped Gardens", "Gym", "24/7 Security"],
    image: "/properties/goyal-orchid.jpg"
  },

  // Tier 3 Cities - Lucknow
  {
    id: 18,
    name: "Sikka Karma",
    location: "Gomti Nagar, Lucknow",
    city: "Lucknow",
    price: 75,
    priceUnit: "Lakh",
    currency: "INR",
    type: "Apartment",
    bedrooms: 2,
    size: 1150,
    status: "Under Construction",
    builder: "Sikka Group",
    features: ["Swimming Pool", "Clubhouse", "Jogging Track"],
    image: "/properties/sikka-karma.jpg"
  },

  // International Properties (Dubai)
  {
    id: 19,
    name: "Emaar Beachfront",
    location: "Dubai Harbour",
    city: "Dubai",
    price: 3.2,
    priceUnit: "Million",
    currency: "AED",
    type: "Apartment",
    bedrooms: 2,
    size: 1200,
    status: "Under Construction",
    builder: "Emaar",
    features: ["Private Beach Access", "Infinity Pool", "Marina Views"],
    image: "/properties/emaar-beachfront.jpg"
  },
  {
    id: 20,
    name: "Palm Jumeirah Signature Villas",
    location: "Palm Jumeirah",
    city: "Dubai",
    price: 18,
    priceUnit: "Million",
    currency: "AED",
    type: "Villa",
    bedrooms: 6,
    size: 7000,
    status: "Ready to Move",
    builder: "Nakheel",
    features: ["Private Beach", "Home Theater", "Yacht Dock"],
    image: "/properties/palm-villas.jpg"
  }
];